USE [master]
GO
/****** Object:  Database [Staging]    Script Date: 09/12/2023 02:35:49 ******/
CREATE DATABASE [Staging]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Staging', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Staging.mdf' , SIZE = 2105344KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Staging_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Staging_log.ldf' , SIZE = 1449984KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Staging] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Staging].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Staging] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Staging] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Staging] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Staging] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Staging] SET ARITHABORT OFF 
GO
ALTER DATABASE [Staging] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Staging] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Staging] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Staging] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Staging] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Staging] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Staging] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Staging] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Staging] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Staging] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Staging] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Staging] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Staging] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Staging] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Staging] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Staging] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Staging] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Staging] SET RECOVERY FULL 
GO
ALTER DATABASE [Staging] SET  MULTI_USER 
GO
ALTER DATABASE [Staging] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Staging] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Staging] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Staging] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Staging] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Staging] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Staging', N'ON'
GO
ALTER DATABASE [Staging] SET QUERY_STORE = ON
GO
ALTER DATABASE [Staging] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Staging]
GO
/****** Object:  Table [dbo].[hulutitles]    Script Date: 09/12/2023 02:35:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[hulutitles](
	[title] [nvarchar](max) NULL,
	[year] [decimal](18, 0) NULL,
	[date_added] [datetime] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[imdbratings]    Script Date: 09/12/2023 02:35:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[imdbratings](
	[tconst] [nvarchar](15) NULL,
	[averageRating] [float] NULL,
	[numVotes] [decimal](18, 0) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[imdbtitles]    Script Date: 09/12/2023 02:35:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[imdbtitles](
	[tconst] [nvarchar](15) NULL,
	[titleType] [nvarchar](15) NULL,
	[primaryTitle] [nvarchar](500) NULL,
	[originalTitle] [nvarchar](500) NULL,
	[isAdult] [decimal](18, 0) NULL,
	[startYear] [decimal](18, 0) NULL,
	[endYear] [decimal](18, 0) NULL,
	[runtimeMinutes] [nvarchar](30) NULL,
	[genres] [nvarchar](250) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ratings]    Script Date: 09/12/2023 02:35:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ratings](
	[title] [nvarchar](150) NULL,
	[year] [decimal](18, 0) NULL,
	[score] [float] NULL,
	[num_of_votes] [decimal](18, 0) NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [ClusteredIndex-20231207-041834]    Script Date: 09/12/2023 02:35:49 ******/
CREATE CLUSTERED INDEX [ClusteredIndex-20231207-041834] ON [dbo].[ratings]
(
	[title] ASC,
	[year] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[titles]    Script Date: 09/12/2023 02:35:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[titles](
	[id] [nvarchar](150) NULL,
	[title] [nvarchar](max) NOT NULL,
	[year] [decimal](18, 0) NULL,
	[date_added] [datetime] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [ClusteredIndex-20231207-041807]    Script Date: 09/12/2023 02:35:49 ******/
CREATE CLUSTERED INDEX [ClusteredIndex-20231207-041807] ON [dbo].[titles]
(
	[id] ASC,
	[year] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Staging] SET  READ_WRITE 
GO
